name = "Hugo Winston"
license = "MIT"
licenselink = "https://github.com/zerostaticthemes/hugo-winston/blob/master/LICENSE"
description = "Hugo Winston is a bold minimal blogging theme"

homepage = "https://github.com/zerostaticthemes/hugo-winston-theme"
demosite = "https://hugo-winston.netlify.app"

tags = ["blog", "minimal", "clean", "zerostatic"]
features = ["blog", "anchor-links"]

[params]
  # Enable anchor links for headings
  anchorLinks = true
  # Optional: Configure anchor link symbol
  anchorSymbol = "#"

[author]
  name = "Robert Austin"
  homepage = "https://www.zerostatic.io"
